import "@/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";

import { SiteHeader } from "@/components/site-header";
import { ThemeProvider } from "@/components/theme-provider";
import { buttonVariants } from "@/components/ui/button";
import { Toaster } from "@/components/ui/sonner";
import { TRPCReactProvider } from "@/trpc/react";

// TODO: add metadata titles to all pages, favicon, site fonts, etc.
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${GeistSans.variable}`}
    >
      <body className="bg-base text-foreground">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider
            appearance={{
              elements: {
                card: "bg-background text-foreground",
                footer: "[background:hsl(var(--background))] text-foreground",
                input:
                  "flex h-10 w-full rounded-md !border border-input hover:!border hover:!border-input/80 focus:!border-input/80 bg-background text-foreground px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
                formFieldLabel:
                  "text-sm font-medium text-foreground leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
                footerActionText: "text-foreground",
                footerActionLink: "text-muted-foreground",
                userButtonPopoverCard:
                  "bg-background text-foreground shadow-lg shadow-foreground/20 border-t border-t-foreground/20",
                userButtonPopoverMain:
                  "bg-background text-foreground hover:text-foreground",
                userButtonPopoverActions:
                  "bg-background text-foreground hover:text-foreground",
                userButtonPopoverActionButton:
                  "bg-background text-foreground hover:text-foreground/85 relative before:absolute before:top-0 before:w-full before:border-muted before:border-t",
                userButtonPopoverFooter:
                  "[background:hsl(var(--background))] text-foreground",
                formButtonPrimary: buttonVariants({ variant: "default" }),
                formFieldInputShowPasswordButton: buttonVariants({
                  variant: "ghost",
                }),
                formFieldInputShowPasswordIcon:
                  "text-muted-foreground hover:text-foreground",
                header: "hidden",
              },
            }}
          >
            <div
              className="grid min-h-screen grid-rows-[minmax(5vh,auto)_1fr]"
              style={{ minHeight: "100dvh" }}
            >
              <SiteHeader />
              <TRPCReactProvider>{children}</TRPCReactProvider>
              <Toaster position="top-right" closeButton richColors />
            </div>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
