import "@/styles/globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { GeistSans } from "geist/font/sans";

import { SiteHeader } from "@/components/site-header";
import { ThemeProvider } from "@/components/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { clerkAppearance } from "@/styles/clerk-appearance";
import { TRPCReactProvider } from "@/trpc/react";
import clerkAppearance from "@/styles/clerk-appearance.json";

// TODO: add metadata titles to all pages, favicon, site fonts, etc.
export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${GeistSans.variable}`}
    >
      <body className="bg-base text-foreground">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <ClerkProvider appearance={clerkAppearance}>
            <div
              className="grid min-h-screen grid-rows-[minmax(5vh,auto)_1fr]"
              style={{ minHeight: "100dvh" }}
            >
              <SiteHeader />
              <TRPCReactProvider>{children}</TRPCReactProvider>
              <Toaster position="top-right" closeButton richColors />
            </div>
          </ClerkProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
